version: '3.8'
services:
  app:
    container_name: app-python
    build: ./services/prj
    command: "python main.py"
    env_file:
      - ./.dev.env
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=pstgres1!
      - POSTGRES_PASSWORD=pstgres1!
    ports:
      - '5442:5432'
    volumes: 
     - db1:/var/lib/postgresql/data


volumes:
 db1:
